Unmanic/unmanic

- webserver/templates/page_layout.html
This will give mixed contents error when reverse proxying the app using https.
> removed http

- unmanic/libs/ffmpeg.py
Fixing the PR for force-audio-conversion-based-off-of-audio-config without bring other changes
> force-audio-conversion-based-off-of-audio-config-rebase

- .github/workflows/integration_test_and_build_all_packages_ci.yml
- docker/Dockerfile
Since the migration to Unmanic org, some parts of actions stopped working (i think).
This fixes it and adds some improvements.
> Update GitHub actions

- tests/integration/test_ffmpeg.py
- tests/integration/test_taskhandler.py
- tests/integration/test_worker.py
- unmanic/config.py
- unmanic/libs/common.py
- unmanic/libs/eventmonitor.py
- unmanic/libs/ffmpeg.py
- unmanic/libs/filetest.py
- unmanic/libs/postprocessor.py
- unmanic/libs/task.py
- unmanic/libs/unmodels/__init__.py
- unmanic/libs/unmodels/basemodel.py
- unmanic/libs/unmodels/installation.py
- unmanic/libs/unmodels/settings.py
- unmanic/libs/unplugins/executor.py
- unmanic/libs/unplugins/plugin_types/library_management/__init__.py
- unmanic/libs/unplugins/plugin_types/library_management/file_test.py
- unmanic/libs/unplugins/plugin_types/postprocessor/file_move.py
- unmanic/libs/unplugins/plugin_types/postprocessor/task_result.py
- unmanic/service.py
- unmanic/webserver/api_v1/plugins_api.py
- unmanic/webserver/assets/global/plugins/extendible-bbcode-parser/xbbcode.css
- unmanic/webserver/assets/global/plugins/extendible-bbcode-parser/xbbcode.js
- unmanic/webserver/assets/pages/scripts/templates.js
- unmanic/webserver/assets/templates/plugins/plugin-info.hbs
- unmanic/webserver/templates/page_layout.html
> Develop library management plugins

- docker/Dockerfile
Add Intel Media Drivers for gen 8+ Intel GPU.
https://github.com/intel/media-driver
> Update Ubuntu to Focal and add Intel Media Drivers

- .github/FUNDING.yml
I've suddenly discovered a typo in your Patreon account linked here on GitHub, this PR fixes it (I hope [Josh5](https://www.patreon.com/josh5) is your account, but Josh.5 leads to 404 anyway). I assume you wouldn't mind that I'm creating the PR into `master`, sorry in advance if you do :)
> [FUNDING.yml] fix Patreon link

- requirements.txt
- tests/integration/test_taskhandler.py
- tests/integration/test_worker.py
- unmanic/libs/common.py
- unmanic/libs/ffmpeg.py
- unmanic/libs/history.py
- unmanic/libs/plugins.py
- unmanic/libs/postprocessor.py
- unmanic/libs/session.py
- unmanic/libs/task.py
- unmanic/libs/unmodels/basemodel.py
- unmanic/libs/unplugins/pluginscli.py
- unmanic/service.py
> Fix connection issues with Db that lead to exception: "sqlite3.OperationalError: database is locked" 

- docker/Dockerfile
> (FEATURE DOCKER FFMPEG UPDATE) Update ffmpeg binary in the docker image

- unmanic/libs/common.py
- unmanic/libs/filetest.py
- unmanic/libs/foreman.py
- unmanic/libs/plugins.py
- unmanic/libs/postprocessor.py
- unmanic/libs/unplugins/executor.py
- unmanic/libs/unplugins/settings.py
- unmanic/libs/workers.py
- unmanic/webserver/helpers/plugins.py
- unmanic/webserver/plugins.py
> Improvements to Plugin importing and RAM garbage collection

- unmanic/libs/scheduler.py
- unmanic/libs/session.py
This pushes out the requirement for the session to be updated every 24 hours but still attempts to update it every hour.
> Fix for people who have poor internet connections.

- .idea/inspectionProfiles/Project_Default.xml
- .idea/misc.xml
- docker/Dockerfile
- unmanic/libs/common.py
- unmanic/libs/postprocessor.py
- unmanic/libs/task.py
- unmanic/libs/unmodels/tasks.py
- unmanic/webserver/api_v2/__init__.py
- unmanic/webserver/api_v2/base_api_handler.py
- unmanic/webserver/api_v2/history_api.py
- unmanic/webserver/api_v2/pending_api.py
- unmanic/webserver/api_v2/plugins_api.py
- unmanic/webserver/api_v2/schema/schemas.py
- unmanic/webserver/api_v2/session_api.py
- unmanic/webserver/api_v2/settings_api.py
- unmanic/webserver/api_v2/upload_api.py
- unmanic/webserver/api_v2/workers_api.py
- unmanic/webserver/docs/api_schema_v2.json
- unmanic/webserver/docs/api_schema_v2.yaml
- unmanic/webserver/helpers/pending_tasks.py
> (FEATURE: Distributed computing) Phase #1

- devops/run_docker.sh
- requirements.txt
- unmanic/config.py
- unmanic/libs/foreman.py
- unmanic/libs/installation_link.py
- unmanic/libs/postprocessor.py
- unmanic/libs/scheduler.py
- unmanic/libs/session.py
- unmanic/libs/system.py
- unmanic/libs/task.py
- unmanic/libs/uiserver.py
- unmanic/libs/workers.py
- unmanic/webserver/api_v2/pending_api.py
- unmanic/webserver/api_v2/schema/schemas.py
- unmanic/webserver/api_v2/settings_api.py
- unmanic/webserver/api_v2/upload_api.py
- unmanic/webserver/api_v2/workers_api.py
- unmanic/webserver/docs/api_schema_v2.json
- unmanic/webserver/docs/api_schema_v2.yaml
- unmanic/webserver/downloads.py
> (FEATURE: Remote Installation Linking) 

- docker/Dockerfile
- unmanic/libs/filetest.py
- unmanic/libs/libraryscanner.py
- unmanic/libs/unplugins/executor.py
> Improvements to library scanning

- setup.py
- unmanic/__main__.py
- unmanic/config.py
- unmanic/libs/common.py
- unmanic/libs/library.py
- unmanic/service.py
- unmanic/webserver/helpers/filebrowser.py
> (FEATURE: Windows support) 

- requirements.txt
Upgrade peewee-migrate to the latest version.  This is in reference to https://github.com/Unmanic/unmanic-documentation/pull/15
> Upgrade peewee-migrate to support Python 3.10

- .github/workflows/integration_test_and_build_all_packages_ci.yml
- .github/workflows/python_lint_and_run_unit_tests.yml
- requirements-dev.txt
- unmanic/libs/db_migrate.py
- unmanic/libs/unmodels/__init__.py
Fixes issue https://github.com/Unmanic/unmanic/issues/368 relating to peewee migrations failing on subsequent launches.  Also includes a slight refactor to the dynamic model loading code to avoid having to maintain a list of classes.
> Refactor peewee migrations to avoid error on subsequent launches

- unmanic/libs/library.py
Fix minor typo in the library adjective list
> Fix unexpected concatenation in the library adjectives

- docker/Dockerfile
Update reference to libxml2 package to a version that exists.
> Update libxml2 version due to previous version being unavailable

- docker/Dockerfile
Update docker file package version to allow builds to succeed
> Update libexpat1 package to one that exists

- docker/README.md
Added missing step from Docker build documentation, which previously would cause `npm` errors because of the missing frontend.
> Add git submodule update command to docker build process documentation

- unmanic/libs/workers.py
Building on what we discussed in discord https://discord.com/channels/819327740279914516/828703056971169822/1257862130858721280
> don't try and create dir if file_out is None

- unmanic/libs/unplugins/pluginscli.py
Fix incorrect documentation link in `pluginscli.py`. Fixes #568
> Update plugin runner documentation link in PluginsCLI
